### ISSUE TITLE
add axios fetch

### ISSUE THREAD

**Issue by rumsky** [borekb/nextjs-with-mobx#5]
Hi, thank you very much. Could you add axios example .

**Comment by borekb** [comment]
You'd just replace [these lines](https://github.com/borekb/nextjs-with-mobx/blob/359987ffba3d193060f7dff2fc74a8893a95bceb/utils/api.js#L2-L6) with something like:

```js
const response = await axios.get(...);
return response;
```

Would that work for you? I'd like to keep the example agnostic of any particular data fetching libraries.

**Comment by rumsky** [comment]
OK
