### ISSUE TITLE
Why use React.createContext instead of mobx-react.Provider

### ISSUE THREAD

**Issue by rumsky** [borekb/nextjs-with-mobx#6]
Hi, Why use React.createContext instead of mobx-react.Provider 
Could you provide an example how to use mobx-react.Provider and use decorators like this?

_app.js:
` <Provider store={this.store}>`

somePage.js:
` import React, { Component } from \'react\';
import { inject, observer } from \'mobx-react\';

@inject(\'store\')
@observer
class Blocks extends Component {
  static async getInitialProps({store}) {
  
  }

  constructor(props) {
    super(props);
    this.store = this.props.store.blocksStore;
  }
} `

**Comment by borekb** [comment]
It should work very similarly with MobX provider – just put it to the `render` function inside `_app.js`.

As to why I used React context instead of MobX `<Provider>`:

> Note: usually there is no need anymore to use `Provider` / `inject` in new code bases; most of its features are now covered by `React.createContext`.

[Source](https://github.com/mobxjs/mobx-react/blob/c27fc785051c378aa23fe4f205ddac06285f1b62/README.md#provider-and-inject).
